"""add cash 4 life drawing

Revision ID: 522b6f73ea80
Revises: a8d75e978d9f
Create Date: 2025-05-18 17:43:50.887518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '522b6f73ea80'
down_revision: Union[str, None] = 'a8d75e978d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_4_life_drawings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_ball', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('second_ball', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('third_ball', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fourth_ball', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fifth_ball', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cash_ball', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_drawn', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cash_4_life_drawings_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_4_life_drawings')
    # ### end Alembic commands ###
