"""Create drawings

Revision ID: 8e2c1421fefd
Revises: 
Create Date: 2025-03-14 16:00:27.786388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2c1421fefd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drawings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_ball', sa.Integer(), nullable=True),
    sa.Column('second_ball', sa.Integer(), nullable=True),
    sa.Column('third_ball', sa.Integer(), nullable=True),
    sa.Column('fourth_ball', sa.Integer(), nullable=True),
    sa.Column('fifth_ball', sa.Integer(), nullable=True),
    sa.Column('power_ball', sa.Integer(), nullable=True),
    sa.Column('date_drawn', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drawings')
    # ### end Alembic commands ###
