"""create generations

Revision ID: a8d75e978d9f
Revises: 8e2c1421fefd
Create Date: 2025-04-21 18:25:55.582829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d75e978d9f'
down_revision: Union[str, None] = '8e2c1421fefd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_ball', sa.Integer(), nullable=True),
    sa.Column('second_ball', sa.Integer(), nullable=True),
    sa.Column('third_ball', sa.Integer(), nullable=True),
    sa.Column('fourth_ball', sa.Integer(), nullable=True),
    sa.Column('fifth_ball', sa.Integer(), nullable=True),
    sa.Column('power_ball', sa.Integer(), nullable=True),
    sa.Column('date_generated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('generations')
    # ### end Alembic commands ###
